package com.example.physics_lab.utils

object SharedPrefConstants {
    const val NAME = "SHARED_PREF_NAME"
    const val NAME_LAB = "SHARED_PREF_NAME_LAB"
    const val USER_TOKEN = "USER_TOKEN"
    const val USER_ROLE = "USER_ROLE"
    const val CLASS_ID = "CLASS_ID"
    const val CLASS_TITLE = "CLASS_TITLE"
    const val CLASS_CODE = "CLASS_CODE"
    const val LAB_DESCRIPTION = "LAB_DESCRIPTION"
    const val LAB_ID = "LAB_ID"
    const val LAB_EQUIP = "LAB_EQUIP"
    const val LAB_NAME = "LAB_NAME"
    const val LAB_THEME = "LAB_THEME"
    const val LAB_VIDEO = "LAB_VIDEO"
    const val SOLUTION_NAME = "SOLUTION_NAME"
    const val SOLUTION_USER_ID = "SOLUTION_USER_ID"
    const val SOLUTION_RESULT = "SOLUTION_RESULT"
    const val SOLUTION_DATE = "SOLUTION_DATE"
    const val SOLUTION_VIDEO = "SOLUTION_VIDEO"
    const val REGISTRATION_EMAIL = "REGISTRATION_EMAIL"
    const val REGISTRATION_PASSWORD = "REGISTRATION_PASSWORD"
    const val REGISTRATION_FULL_NAME = "REGISTRATION_FULL_NAME"
    const val REGISTRATION_ROLE = "REGISTRATION_ROLE"
    const val STATIC_PREV_LAYOUT = "STATIC_PREV_LAYOUT"
    const val STATIC_COUNT_CLASSES = "STATIC_COUNT_CLASSES"
    const val STATIC_COUNT_LABS = "STATIC_COUNT_LABS"
    const val STATIC_COUNT_USERS = "STATIC_COUNT_USERS"
}